Merged PR 19240: Fix incorrect brackets in generate_golden_config_db.py
Fix incorrect brackets in generate_golden_config_db.py

 * A previous merge from public caused an incorrect brackets which causes
   deploy-mg to fail on internal-202511

```
TASK [Generate golden_config_db.json] ******************************************
task path: /azp/_work/2/s/ansible/config_sonic_basedon_testbed.yml:750
fatal: [str3-8102-smartswitch-02]: FAILED! => {"changed": false, "module_stderr": "OpenSSH_9.6p1 Ubuntu-3ubuntu13.14, OpenSSL 3.0.13 30 Jan 2024\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 10.3.146.224 is address\r\ndebug1: auto-mux: Trying existing master at '/root/.ansible/cp/2798787200'\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug1: mux_client_request_session: master session id: 2\r\nTraceback (most recent call last):\n  File \"<stdin>\", line 107, in <module>\n  File \"<stdin>\", line 99, in _ansiballz_main\n  File \"<stdin>\", line 47, in invoke_module\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_generate_golden_config_db_payload_90kfwvln/ansible_generate_golden_config_db_payload.zip/ansible/modules/generate_golden_config_db.py\", line 699, in <module>\n  File \"/tmp/ansible_generate_golden_config_db_payload_90kfwvln/ansible_generate_golden_config_db_payload.zip/ansible/modules/generate_golden_config_db.py\", line 694, in main\n  File \"/tmp/ansible_generate_golden_config_db_payload_90kfwvln/ansible_generate_golden_config_db_payload.zip/ansible/modules/generate_golden_config_db.py\", line 56, in __init__\n  File \"/tmp/ansible_generate_golden_config_db_payload_90kfwvln/ansible_generate_golden_config_db_payload.zip/ansible/module_utils/basic.py\", line 419, in __init__\n  File \"/tmp/ansible_generate_golden_config_db_payload_90kfwvln/ansible_generate_golden_config_db_payload.zip/ansible/module_utils/common/arg_spec.py\", line 297, in __init__\n  File \"/tmp/ansible_generate_golden_config_db_payload_90kfwvln/ansible_generate_golden_config_db_payload.zip/ansible/module_utils/common/arg_spec.py\", line 139, in __init__\nAttributeError: 'bool' object has no attribute 'get'\ndebug2: Received exit status from master 1\r\n", "module_stdout": "", "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error", "rc": 1}

 ```

Signed-off-by: Prabhat Aravind <paravind@microsoft.com>

----
#### AI description  (iteration 1)
#### PR Classification
Bug fix addressing incorrect bracket usage and parameter ordering in module configuration.

#### PR Summary
This pull request corrects the configuration of parameters in the `generate_golden_config_db.py` module by fixing the misplaced closing bracket and removing a ...